# Generated by Django 5.0.6 on 2024-05-18 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0002_rename_despesas_despesa'),
        ('integrantes', '0001_initial'),
        ('rendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Integrantes',
            new_name='Integrante',
        ),
    ]
