# Generated by Django 5.0.6 on 2024-05-18 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrantes.integrantes')),
            ],
        ),
    ]
