# Generated by Django 5.0.6 on 2024-05-18 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrantes', '0002_rename_integrantes_integrante'),
        ('rendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rendas',
            new_name='Renda',
        ),
    ]
